// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Xp-yDueT9gB4kUMz__CZevTaqhsDThA',
    appId: '1:1083247392493:web:d12a636194723fbe717ee4',
    messagingSenderId: '1083247392493',
    projectId: 'meowtalk-dc6e5',
    authDomain: 'meowtalk-dc6e5.firebaseapp.com',
    storageBucket: 'meowtalk-dc6e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9VFTLXJg80F6PnAQCd8wCnpytP_zV5n0',
    appId: '1:1083247392493:android:eeb115a54ab8a329717ee4',
    messagingSenderId: '1083247392493',
    projectId: 'meowtalk-dc6e5',
    storageBucket: 'meowtalk-dc6e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4cXuW5wo_SNl2X081jNCrft1n4rCY5c4',
    appId: '1:1083247392493:ios:86b876ff28980ec2717ee4',
    messagingSenderId: '1083247392493',
    projectId: 'meowtalk-dc6e5',
    storageBucket: 'meowtalk-dc6e5.appspot.com',
    iosBundleId: 'com.example.meowtalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4cXuW5wo_SNl2X081jNCrft1n4rCY5c4',
    appId: '1:1083247392493:ios:86b876ff28980ec2717ee4',
    messagingSenderId: '1083247392493',
    projectId: 'meowtalk-dc6e5',
    storageBucket: 'meowtalk-dc6e5.appspot.com',
    iosBundleId: 'com.example.meowtalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5Xp-yDueT9gB4kUMz__CZevTaqhsDThA',
    appId: '1:1083247392493:web:5514399fa300299f717ee4',
    messagingSenderId: '1083247392493',
    projectId: 'meowtalk-dc6e5',
    authDomain: 'meowtalk-dc6e5.firebaseapp.com',
    storageBucket: 'meowtalk-dc6e5.appspot.com',
  );
}
